# Generated by Django 5.1.6 on 2025-03-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('visa', 'Visa'), ('mastercard', 'Mastercard'), ('paypal', 'PayPal')], max_length=20),
        ),
    ]
