# Generated by Django 5.1.6 on 2025-03-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('cashin', 'Cash In'), ('withdrawal', 'Withdrawal')], default='cash-in', max_length=10),
            preserve_default=False,
        ),
    ]
